### ISSUE TITLE
Dynamically adding issue

### ISSUE THREAD

**Issue by tibigeorgescu90** [ranvijaySingh-Webonise/AdjustableLayout#1]
Hi,

Congrats on the layout, works very nice on a sequential on click action, however if I want to dynamically add multiple views, say after a multiple choice action, I adds all on one single row, and basically acts like a regular LinearLayout so it doesn't show all views.

Any idea how to solve this?

Thanks

**Comment by RanaRanvijaySingh** [comment]
Hi,
Sorry for not documenting the multiple view feature. I will do that right away. 
Adding multiple view is a bit different than the conventional way.
/**
     \* Function to add view in a loop
     _/
    private void addViewInALoop() {
        for (int i=0;i<stringList.size();i++){
            final View newView = LayoutInflater.from(this).inflate(R.layout.view_chip_text,null);
            TextView tvName = (TextView)newView.findViewById(R.id.tvName);
            ImageView ivRemove = (ImageView)newView.findViewById(R.id.ivRemove);
            ivRemove.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View view) {
                    adjustableLayout.removeView(newView);
                }
            });
            tvName.setText(stringList.get(i));
            *_adjustableLayout.addingMultipleView(newView);**
        }
       *\* adjustableLayout.invalidateView();**
    }

I hope this will solve your problem 
NOTE : There is still few bugs in this code.

**Comment by tibigeorgescu90** [comment]
super, it worked, thanks a lot, and thank you for the promptitude of your answer :)

**Comment by RanaRanvijaySingh** [comment]
FIXED
