### ISSUE TITLE
Clear views and add again

### ISSUE THREAD

**Issue by ajdeguzman** [ranvijaySingh-Webonise/AdjustableLayout#2]
Is there a way how to clear views then able to add again?

**Comment by RanaRanvijaySingh** [comment]
Sorry, i did not understand what you meant by clear view.
If you want to delete a view from the layout and add again then YES you can do that.
You simply need to call delete view function and addview one by one.

**Comment by ajdeguzman** [comment]
What I meant is to clear all the views (without clicking the 'x' button) then populate it again with the list.

**Comment by RanaRanvijaySingh** [comment]
Yes you can do that. You need to call adjustableLayout.removeAllViews().

**Comment by ajdeguzman** [comment]
I just did that. I'm using your library together with Reyclerview containing checkboxes. Everytime you select in Recyclerview, it must appear in the AdjustableLayout. Using the `adjustableLayout.removeAllViews()` after `findViewById(R.id.adjustableLayout)` remove all views but unable to add view again

**Comment by RanaRanvijaySingh** [comment]
Thank you for finding this issue. I really appreciate it. 
I have fixed this issue. 

Added few new codes in AdjustableLayout class.
You can pick those lines and simply add it in you file or you can pull this branch **feature-remove-view**

I have marked those new lines with a comment, something like this : 
//>>>>>>>>>>>>>>>>>>>>>> ISSUE : Clear views and add again>>>>>>>>>>>>>

**Comment by RanaRanvijaySingh** [comment]
**Code updated in master and develop**

**Comment by ajdeguzman** [comment]
So basically you just created and overrided `removeAllViews()` method. Thank you.

**Comment by RanaRanvijaySingh** [comment]
Yes, you welcome. :)

**Comment by RanaRanvijaySingh** [comment]
Fixed.
