### ISSUE TITLE
TextView not showing text

### ISSUE THREAD

**Issue by kprashantxstpl** [ranvijaySingh-Webonise/AdjustableLayout#3]
Adding multiple views in adjustablelayout but many times not showing the textview text like below image

Below is my code

`  adjustableLayoutInterest.removeAllViews();

```
        for (int i = 0; i < userInformationModel.preferencesList.size(); i++) {

            if (userInformationModel.preferencesList.get(i).getIsActive() == 1) {

                final View newView = LayoutInflater.from(this).inflate(R.layout.view_chip_group, null);
                TextView tvName = (TextView) newView.findViewById(R.id.txtGroupName);
                ImageView imgGroupIcon = (ImageView) newView.findViewById(R.id.imgGroupIcon);
                tvName.setText("" + userInformationModel.preferencesList.get(i).getChildCategory());
                tvName.setTextColor(getResources().getColor(R.color.black));
                adjustableLayoutInterest.addingMultipleView(newView); } }
        adjustableLayoutInterest.invalidateView();`
```

![autolayout](https://cloud.githubusercontent.com/assets/13027872/16655410/d1196566-4477-11e6-8010-7faa537b78e4.png)

**Comment by RanaRanvijaySingh** [comment]
Hey, i was not able to produce your issue. But i was able to create a your requirement on one of my branch. Checkout branch **"issue-kprashantxstpl" > MainActivity**. Preview of the code is attached below. I had to create a new layout file for **"chips (view_chip_text.xml)"** and a drawable file **"user_pic_drawable.xml"**. 
If still you are not getting your desired result then plz let me know. 
You might have to share your code snippet with me if its ok with you.
![screenshot_20160708-093308](https://cloud.githubusercontent.com/assets/4836122/16677152/2d50d8dc-44f0-11e6-965c-3749fb333452.png)

**Comment by RanaRanvijaySingh** [comment]
FIXED
